apiVersion: v2
dependencies:
- name: thanos
  repository: https://charts.bitnami.com/bitnami
  version: 15.6.0
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.5.0
name: thanos
version: "0"
